import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./comon/Header";
import Footer from "./comon/Footer";
import Mainlayout from "./mainlayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Monsta Furiture Exclusive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Mainlayout>

          <Header />
          {children}
          <Footer />

        </Mainlayout>
      </body>
    </html>
  );
}
